# Generated by Django 4.2.8 on 2023-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="news/videos/"),
                ),
                ("photo1", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo2", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo3", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo4", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo5", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo6", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo7", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo8", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo9", models.ImageField(blank=True, upload_to="news/photos/")),
                ("photo10", models.ImageField(blank=True, upload_to="news/photos/")),
            ],
        ),
        migrations.DeleteModel(name="News",),
        migrations.DeleteModel(name="Photo",),
    ]
