# Generated by Django 4.2.8 on 2024-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_post_delete_news_delete_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20, verbose_name="Time")),
                (
                    "monday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Monday",
                    ),
                ),
                (
                    "tuesday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Tuesday",
                    ),
                ),
                (
                    "wednesday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Wednesday",
                    ),
                ),
                (
                    "thursday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Thursday",
                    ),
                ),
                (
                    "friday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Friday",
                    ),
                ),
                (
                    "saturday",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Beginners", "Beginners"),
                            ("Children", "Children"),
                            ("Sparring", "Sparring"),
                            ("Basic Course", "Basic Course"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=12,
                        verbose_name="Saturday",
                    ),
                ),
            ],
            options={"verbose_name": "Shedule", "verbose_name_plural": "Shedules",},
        ),
    ]
