# Generated by Django 4.2.8 on 2024-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_price_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="phone_number",),
        migrations.AddField(
            model_name="contact",
            name="company_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="company_name"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number1",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone_number1"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number2",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone_number2"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="account_number",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="company_address"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=300, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="registration_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
