# Generated by Django 4.2.8 on 2024-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_sentemail_alter_contact_account_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="SentEmail",),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(
                blank=True, max_length=300, null=True, verbose_name="email"
            ),
        ),
    ]
